# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[kubernetes]
format = '[âˆ $context (\($namespace\))](#326ce5) '
disabled = false

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "$cluster"

[gcloud]
symbol = 'ï¸ğŸ‡¬ï¸'
format = 'on [$symbol$project]($style) '

